### ISSUE TITLE
find_all error in kg download

### ISSUE THREAD

**Issue by nitish11** [floydwch/kaggle-cli#18]
I got error while running the download command. 

`kg download -u '******' -p '******' --competition 'https://www.kaggle.com/c/data-science-bowl-2017'`

I got the following error:
```

Starting new HTTPS connection (1): www.kaggle.com
'NoneType' object has no attribute 'find_all'

```

Any suggestions??

**Comment by igorbarinov** [comment]
@nitish11 to me accepting ToS on kaggle website helped with the same error

**Comment by nitish11** [comment]
After accepting ToS, the below command is the accepted solution.

`kg download -u '******' -p '******' --competition 'data-science-bowl-2017'`

**Comment by msgrasser** [comment]
Still getting this error (with 'dogs-vs-cats' competition, after accepting TOS), and it looks to be due to line 27 of download.py – it's looking for an element with an id that doesn't exist, then trying to find 'a' elements within that. 

Looks like kaggle switched to react and doesn't display all download links anymore – could this have something to do with it or am I missing something?

**Comment by calliope7** [comment]
Hey msgrasser - this has been thwarting me as well..  your comments made me think.. I wonder if I reinstall kg.. when I tried, I found that pip was out of date..  'pip install --upgrade pip' solved that.. followed by 'pip install --upgrade kaggle-cli'.  Now when I run kg download.. it works!  Hope this helps.

**Comment by msgrasser** [comment]
Super helpful, calliope7, will try that – thank you very much!

**Comment by msgrasser** [comment]
Haha, so it looks like in the time between my comment and your comment there was [another issue + subsequent PR](https://github.com/floydwch/kaggle-cli/issues/22) that addressed this.

pip being out of date wasn't actually the cause - the cause was in fact what I had hypothesized regarding the dynamic content generation for kaggle's web app. Regardless, when you upgraded kaggle-cli you must've caught that latest update made in the PR mentioned above. 

Thanks for the tip, and I'm super glad to see how active this repo is!

**Comment by calliope7** [comment]
Yup that looks like it.. Thanks for the followup.

**Comment by shubchat** [comment]
Hey guys getting-'Response' object has no attribute 'soup' error for all competitions.Any thoughts on how to go about it?

**Comment by shubchat** [comment]
Guys it is solved I needed to put '-' between all words in the competition name and all will be small case
